Reservas\Domain\Pedidos\Entities\PedidoCartao:
    type: entity
    table: reservas.PedidoCartao
    # repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\PedidoCartaoRepository
    id:
        pedido:
            associationKey: true
            id: true
    fields:
        dono:
            type: string
            nullable: false
            length: 100
        numero_cartao:
            type: string
            nullable: false
            length: 20
        validade:
            type: string
            nullable: false
            length: 7
        codigo_seguranca:
            type: string
            nullable: false
            length: 5
        valor:
            type: float
            nullable: false
        parcelas:
            type: integer
            nullable: false
            options:
                default: 1
        tipo:
            type: string
            nullable: false
            length: 10
            options:
                default: 'credit'
    oneToOne:
        pedido:
            targetEntity: Pedido
            inversedBy: cartao
            joinColumns:
                pedido_id:
                    referencedColumnName: pedido_id