Reservas\Domain\Quartos\Entities\QuartoMidia:
    type: entity
    table: reservas.QuartoMidia
    # repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\QuartoMidiaRepository
    id:
        quarto:
            associationKey: true
            id: true
    fields:
        arquivo_original:
            type: string
            nullable: false
            length: 255
            id: true
        miniatura:
            type: string
            nullable: true
            length: 255
    manyToOne:
        quarto:
            targetEntity: Quarto
            inversedBy: midias
            joinColumns:
                quarto_id:
                    referencedColumnName: quarto_id