Reservas\Domain\Disponibilidade\Entities\DisponibilidadeValor:
    type: entity
    table: reservas.DisponibilidadeValor
    # repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\DisponValorRepository
    id:
        disponibilidade:
            associationKey: true
            id: true
        quantidade_pessoas:
            type: integer
            nullable: false
            id: true
    fields:
        valor:
            type: float
            nullable: false
    manyToOne:
        disponibilidade:
            targetEntity: Disponibilidade
            inversedBy: valores
            joinColumns:
                disponibilidade_id:
                    referencedColumnName: disponibilidade_id