Reservas\Domain\Quartos\Entities\Quarto:
    type: entity
    table: dlx_reservas_quartos
    repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\QuartoRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: quarto_id
    fields:
        nome:
            type: string
            nullable: false
            length: 50
            column: quarto_nome
        descricao:
            type: string
            nullable: true
            length: 255
            column: quarto_descricao
        max_hospedes:
            type: integer
            nullable: false
            column: quarto_maxhospedes
        qtde:
            type: integer
            nullable: false
            column: quarto_qtde
        valor_min:
            type: float
            nullable: false
            column: quarto_valor_min
        tamanho_m2:
            type: integer
            nullable: false
            column: quarto_tamanho_m2
        link:
            type: string
            nullable: false
            length: 60
            column: quarto_link
        publicar:
            type: boolean
            nullable: false
            column: quarto_publicar
        deletado:
            type: boolean
            nullable: false
            column: quarto_delete
    oneToMany:
        dispon:
            targetEntity: Reservas\Domain\Disponibilidade\Entities\Disponibilidade
            orderBy: { dia: desc }
            cascade:
                - merge
            mappedBy: quarto
            joinColumns:
                quarto_id:
                    referencedColumnName: dispon_quarto
        midias:
            targetEntity: QuartoMidia
            mappedBy: quarto
            cascade:
                - persist
                - merge
                - remove
            joinColumns:
                quarto_id:
                    referencedColumnName: midia_quarto
