Reservas\Domain\Quartos\Entities\Quarto:
    type: entity
    table: reservas.Quarto
    repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\QuartoRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: quarto_id
    fields:
        nome:
            type: string
            nullable: false
            length: 50
        descricao:
            type: string
            nullable: true
            length: 255
        maximo_hospedes:
            type: integer
            nullable: false
        quantidade:
            type: integer
            nullable: false
        valor_minimo:
            type: float
            nullable: false
        tamanho_m2:
            type: integer
            nullable: false
        link:
            type: string
            nullable: false
            length: 60
        deletado:
            type: boolean
            nullable: false
            options:
                default: false
    oneToMany:
        disponibilidade:
            targetEntity: Reservas\Domain\Disponibilidade\Entities\Disponibilidade
            orderBy: { data: desc }
            cascade:
                - merge
            mappedBy: quarto
            joinColumns:
                quarto_id:
                    referencedColumnName: quarto_id
        midias:
            targetEntity: QuartoMidia
            mappedBy: quarto
            cascade:
                - persist
                - merge
                - remove
            joinColumns:
                quarto_id:
                    referencedColumnName: midia_quarto
