Reservas\Domain\Pedidos\Entities\Pedido:
    type: entity
    table: reservas.Pedido
    repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\PedidoRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: pedido_id
    fields:
        nome:
            type: string
            nullable: false
            length: 50
        cpf:
            type: cpf
            nullable: false
            length: 14
        email:
            type: string
            nullable: false
            length: 200
        telefone:
            type: string
            nullable: true
            length: 16
        valor_total:
            type: float
            nullable: false
        forma_pagamento:
            type: string
            nullable: false
            options:
                default: digitada
        status:
            type: string
            nullable: false
            option:
                default: Pendente
            column: status
    oneToOne:
        cartao:
            targetEntity: PedidoCartao
            mappedBy: pedido
            cascade:
                - persist
            joinColumns:
                pedido_id:
                    referencedColumnName: pedido_id
        endereco:
            targetEntity: PedidoEndereco
            mappedBy: pedido
            cascade:
                - persist
            joinColumns:
                pedido_id:
                    referencedColumnName: pedido_id
    oneToMany:
        itens:
            targetEntity: PedidoItem
            mappedBy: pedido
            orderBy: { checkin: asc }
            cascade:
                - persist
        historico:
            targetEntity: PedidoHistorico
            mappedBy: pedido
            orderBy: { data: desc }
            cascade:
                - persist
            joinColumns:
                pedido_id:
                    referencedColumnName: pedido_id