Reservas\Domain\Reservas\Entities\Reserva:
    type: entity
    table: reservas.Reserva
    repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\ReservaRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: reserva_id
    fields:
        hospede:
            type: string
            nullable: false
            length: 200
        cpf:
            type: cpf
            nullable: false
            length: 14
        telefone:
            type: string
            nullable: true
            length: 18
        email:
            type: string
            nullable: false
            length: 200
        checkin:
            type: datetime
            nullable: false
        checkout:
            type: datetime
            nullable: false
        quantidade_adultos:
            type: integer
            nullable: false
        quantidade_criancas:
            type: integer
            nullable: false
        valor:
            type: float
            nullable: false
        status:
            type: string
            nullable: false
            length: 10
        origem:
            type: string
            nullable: false
            length: 20
    manyToOne:
        quarto:
            targetEntity: Reservas\Domain\Quartos\Entities\Quarto
            joinColumns:
                quarto_id:
                    referencedColumnName: quarto_id
    oneToMany:
        historico:
            targetEntity: ReservaHistorico
            orderBy: { data: desc }
            mappedBy: reserva
            cascade:
                - persist
            joinColumns:
                reserva_id:
                    referencedColumnName: reserva_id
        visualizacoes_cpf:
            targetEntity: VisualizacaoCpf
            orderBy: { data: desc, usuario: asc }
            mappedBy: reserva
            cascade:
                - persist
            joinColumns:
                reserva_id:
                    referencedColumnName: reserva_id
    oneToOne:
        pedido_item:
            targetEntity: Reservas\Domain\Pedidos\Entities\PedidoItem
            mappedBy: reserva
            joinColumns:
                reserva_id:
                    referencedColumnName: reserva_id