Reservas\Domain\Pedidos\Entities\PedidoItem:
    type: entity
    table: reservas.PedidoItem
    repositoryClass: Reservas\Infrastructure\ORM\Doctrine\Repositories\PedidoItemRepository
    id:
        id:
            type: integer
            id: true
            nullable: false
            generator:
                strategy: auto
            column: pedido_item_id
    fields:
        checkin:
            type: datetime
            nullable: false
        checkout:
            type: datetime
            nullable: false
        quantidade:
            type: integer
            nullable: false
        quantidade_adultos:
            type: integer
            nullable: false
        quantidade_criancas:
            type: integer
            nullable: false
        valor_total:
            type: float
            nullable: false
    manyToOne:
        pedido:
            targetEntity: Pedido
            inversedBy: itens
            joinColumns:
                pedido_id:
                    referencedColumnName: pedido_id
        quarto:
            targetEntity: Reservas\Domain\Quartos\Entities\Quarto
            joinColumns:
                quarto_id:
                    referencedColumnName: quarto_id
    oneToMany:
        detalhamento:
            targetEntity: PedidoItemDetalhe
            mappedBy: item
            orderBy: { data: asc }
            cascade:
                - persist
            joinColumns:
                pedido_item_id:
                    referencedColumnName: pedido_item_id
    oneToOne:
        reserva:
            targetEntity: Reservas\Domain\Reservas\Entities\Reserva
            inversedBy: pedido_item
            cascade:
                - persist
            joinColumns:
                reserva_id:
                    referencedColumnName: reserva_id